from .binary import binary_to_num
from .colour_code import colours_to_num
from .hexadecimal import hex_to_alpha
from .input_validation import *
from .keypad import keypad_to_sequence
from .mathematics import letters_to_num
from .multi_buttons import numbers_to_sequence
from .tiles import tiles_to_num
from .timing import string_to_colour
